on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: www176.your-server.de
        username: naschea_0
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftps
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          techstack.*
          LICENSE
